#pragma endian big

#include </home/headass/cppProjects/Mantle/ImHex_Patterns/rttibin.hexpat>
#include </home/headass/cppProjects/Mantle/ImHex_Patterns/rtti_texture.hexpat>
#include </home/headass/cppProjects/Mantle/ImHex_Patterns/rtti_string.hexpat>

float float_at_0xC9 @ 0xC9;
float float_at_0xCD @ 0xCD;
float float_at_0xD1 @ 0xD1;
float float_at_0xD5 @ 0xD5;
float float_at_0xD9 @ 0xD9;
float float_at_0xDD @ 0xDD;
float float_at_0xE1 @ 0xE1;
float float_at_0xE5 @ 0xE5;
rtti_texture_funky uh @ 0xE9;
rtti_string_chunk_u8 rtti_string_chunk_u8_at_0xA2 @ 0xA2;
